stages:
  - preparation
  - testing

image: lorisleiva/laravel-docker:8.0

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

composer:
  stage: preparation
  script:
    - php -v
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  artifacts:
    paths:
      - vendor/
    expire_in: 1 days
    when: always
  cache:
    paths:
      - vendor/

phpcs:
  stage: preparation
  image: registry.gitlab.com/pipeline-components/php-codesniffer:latest
  script:
    - phpcs

unitTests:
  stage: testing
  dependencies:
    - composer
  script:
    - php -v
    - composer test
  artifacts:
    paths:
      - ./vendor/orchestra/testbench-core/laravel/database/deployment_scripts
    expire_in: 1 days
    when: on_failure

sast:
  stage: preparation
  artifacts:
    paths:
      - gl-sast-report.json
include:
  - template: Security/SAST.gitlab-ci.yml
